### ISSUE TITLE
[cli] Connection failing 

### ISSUE THREAD

**Issue by Revaycolizer** [danstepanov/create-expo-stack#1]
Whenever I connect to my app through ADB or qr code after some few minutes it aborts connection and I have to connect it again

**Comment by danstepanov** [comment]
Hey! Can you provide the device details for the android device/simulator as well as the steps you performed to run the app? I'll try to recreate on my end and address it if it's an issue with the library :)

**Comment by Revaycolizer** [comment]
Using Huawei y9 as a testing device and also used npx expo start to start my project

**Comment by danstepanov** [comment]
I will look into this this week, are you using mac or windows?

**Comment by Revaycolizer** [comment]
Windows

**Comment by danstepanov** [comment]
I use a mac so might take me a minute to recreate but i'll just see if it's an issue on mac first

**Comment by Revaycolizer** [comment]
Okay Sir

**Comment by Lokhnor** [comment]
I have the same issue when running a clean expo app, don't think this has anything to do with create-expo-stack.

Device: Samsung S21 Ultra
OS: Ubuntu (WSL2 on windows)

**Comment by Lokhnor** [comment]
> I have the same issue when running a clean expo app, don't think this has anything to do with create-expo-stack.
> 
> Device: Samsung S21 Ultra OS: Ubuntu (WSL2 on windows)

Update: WSL2 is the culprit, just tested on a proper linux machine running ubuntu and did not have any issues.

**Comment by danstepanov** [comment]
@Lokhnor thanks for confirming that this isn't an issue with CES! Closing this for now.
