### ISSUE TITLE
[cli] package manager selection

### ISSUE THREAD

**Issue by Randall71** [danstepanov/create-expo-stack#109]
I think it would be extremely useful if the user could select the package manager of their choice

**Comment by danstepanov** [comment]
@Randall71 Currently, you can pass whichever package manager you'd like by passing in `--npm`, `--yarn`, `--pnpm`, or `--bun`. Did you mean that you'd like it to be part of the core CLI? If so, should it be the first question or one of the last ones?

**Comment by danstepanov** [comment]
Now available in v2.3.2

**Comment by Randall71** [comment]
Hi, sorry for the delay in reply, I was expecting it to be the latest one like what you did, but I see that when you use the latest one and choose another package it uses `npm` again.
![Capture d’écran (397)](https://github.com/danstepanov/create-expo-stack/assets/51382079/9394b8af-3ea3-4dea-aee4-03ea2fc5f142)

**Comment by danstepanov** [comment]
I'll look into this today, thanks for flagging

**Comment by danstepanov** [comment]
@Randall71 do you end up with a yarn.lock or a package-lock.json for that project initialization?

**Comment by danstepanov** [comment]
@Randall71 can you try again with v2.3.3

**Comment by Randall71** [comment]
Just test, all is good now
