### ISSUE TITLE
[cli] incorrect replacement of folder/filename with firebase/supabase

### ISSUE THREAD

**Issue by finnbayer** [danstepanov/create-expo-stack#131]
When using firebase or supabase and end the project name on "...base" (e.g. example-project-firebase or project-base) the path will be replaced incorrectly

How to reproduce ?
npx create-expo-stack@latest example-project-firebase --expo-router --stylesheet --importAlias --firebase --yarn

What was expected ?
The project is initialized in the folder example-project-firebase

What is the actual outcome?
![image](https://github.com/danstepanov/create-expo-stack/assets/115630860/85f4de69-e4c0-4352-a0ac-4ae1c740bbc6)
The `base/` of `example-project-firebase/` will be removed and the files will be created accordingly. 

Possible fix:
in `generateProjectFiles.ts` move the prefixing of the target with the projectName to the end.
Instead of adding it at the beginning l.18 via:
```js
let target = `${projectName}/` + file.replace('.ejs', '');
```
it can be added in the gluegun generate function (l.56) like this
```js
const gen = toolbox.template.generate({
	template,
	target: `./${projectName}/` + target,
	props: {
		authenticationPackage,
		flags,
		navigationPackage,
		projectName,
		packageManager,
		packages,
		stylingPackage
	}
});
```

The tests ran with the exception of  `generates a default project with npm` (timeout, probably unrelated). I also tested it with other projectnames (especially the ones ending/starting/containing base) and it worked.  I would be happy to submit a PR if the fix is to your liking.

**Comment by danstepanov** [comment]
This is gnarly bug haha, your suggested fix should be good! Thanks for finding and reporting, looking forward to the PR.
