### ISSUE TITLE
Rename "drawer" to "tabs + drawer"

### ISSUE THREAD

**Issue by danstepanov** [danstepanov/create-expo-stack#144]
When choosing a navigation type in the cli, you currently select between "stack", "tabs", or "drawer". This is misleading as "drawer" actually includes a tab controller as well.

**Comment by PraveenShinde3** [comment]
can i work on this?

**Comment by danstepanov** [comment]
Go for it

**Comment by PraveenShinde3** [comment]
I was looking at the code but couldn't found where this needs to be changed, can you please help me with this ?

**Comment by danstepanov** [comment]
cli/src/utilities/runCLI.ts

Line 43 and 55

I would also make sure that you've read through the contribution guide linked in the readme of this monorepo

**Comment by PraveenShinde3** [comment]
In the event that someone wishes to work on this, please do so, due to other commitments I will not be able to participate, I apologize for the inconvenience.

**Comment by neerajkumarc** [comment]
I would like to take this.

**Comment by frankcalise** [comment]
@neerajkumarc all yours! ty
