### ISSUE TITLE
Please remain expo-router's raw file structures

### ISSUE THREAD

**Issue by likeSo** [danstepanov/create-expo-stack#157]
I created a project use :`npx create-expo-stack@latest my-expo-app --expo-router --tamagui --bun`, structure:
```shell
app
├── _layout.tsx
├── details.tsx
└── index.tsx

1 directory, 3 files
```
Project created using `npx create-expo-app -t`:
```shell
app
├── (tabs)
│   ├── _layout.tsx
│   ├── index.tsx
│   └── two.tsx
├── +html.tsx
├── [...missing].tsx
├── _layout.tsx
└── modal.tsx

2 directories, 7 files
```

`[...missing].tsx` and `+html.tsx` is important to an expo-router project, please remain these files

**Comment by danstepanov** [comment]
@likeSo Can you elaborate on the importance of `+html.tsx` or link to the relevant documentation? `[...missing].tsx` seems like a nice to have rather than necessary for an expo project but open to why you think it is necessary for create expo stack to include. Also PRs are always welcome.

**Comment by danstepanov** [comment]
this seems to be the documentation for the missing file route? https://docs.expo.dev/router/error-handling/

although, here it is called [...unmatched].tsx

**Comment by likeSo** [comment]
Sorry for replying so late, I have some opinions, but the code implementation of this repo is somewhat different from what I imagined;
What if the process is:
`npx create-expo-app -t` -> choose `Blank` or `Navigation` -> configure `Tamagui` stuff based on the fresh-created project.
This process ensures every project is the latest version of the expo-router

For now, you have to create each file in the `app/` directory manually, and may not be up-to-date with the expo.🤔🤔

**Comment by danstepanov** [comment]
@likeSo this will be available in the next version of create expo stack https://github.com/danstepanov/create-expo-stack/pull/156

I added the files you specified to all expo router templates. Also, I'll be adding support for expo router v3 shortly.

**Comment by danstepanov** [comment]
changes are now live
