### ISSUE TITLE
Fonts are not correctly apply using Tamagui and expo-router on web

### ISSUE THREAD

**Issue by gwenoleR** [danstepanov/create-expo-stack#158]
Hey !

After a fresh install, it seems that the font family and color are not working on web using:
- expo-router
- tamagui

Working well on iOS and Android

<img width="1304" alt="image" src="https://github.com/danstepanov/create-expo-stack/assets/10418241/845bc430-93e8-4281-a011-8892bb5146b7">

## Expected Behavior

The inter Font should be apply to the text and title

## Current Behavior

The browser serve the default font

## Steps to Reproduce

fresh install using this command 
`npx create-expo-stack test-stack --expo-router --tamagui --firebase --import-alias --yarn`

**Comment by danstepanov** [comment]
@gwenoleR thanks for flagging! The tamagui documentation is pretty shit and I'm not entirely sure which configuration would address this, off the top of my head. Are you aware of it? Perhaps @benschac can provide some insight?

**Comment by danstepanov** [comment]
@gwenoleR I think I accidentally closed your PR when pushing to your fork. Can you please re-open? It should be good to go with my latest push.

**Comment by danstepanov** [comment]
I opened and merged the PR and you are credited here: https://github.com/danstepanov/create-expo-stack/pull/156
