### ISSUE TITLE
Parsing error on fresh project creation

### ISSUE THREAD

**Issue by ardaydilek** [danstepanov/create-expo-stack#163]
## Creation Command

`npx create-expo-stack movie-star --expo-router --tamagui --import-alias`

When a project is started with this command, a parsing error is returned on page 404 ([...unmatched.tsx]). The project starts with the square brackets of the options in the <Stack.Screen> not closed.

![image](https://github.com/danstepanov/create-expo-stack/assets/68161516/b95f7979-f085-4771-94ff-80bb8e080e47)

![image](https://github.com/danstepanov/create-expo-stack/assets/68161516/c5d617e9-2bc3-48fa-b00e-bab18e48c35d)

**Comment by danstepanov** [comment]
looking into this

**Comment by danstepanov** [comment]
fixed and released in version 2.3.13, should be available on npm (out now)
