### ISSUE TITLE
[cli] Nice to have CLI flags

### ISSUE THREAD

**Issue by danstepanov** [danstepanov/create-expo-stack#17]
- [ ] importAlias
- [ ] src folder (need a better name for this)

**Comment by frankcalise** [comment]
@danstepanov  Can you add more description here? How on target is this interpretation:

Is `importAlias` to enable the path aliases via `expo.experiments.tsconfigPaths`?

https://docs.expo.dev/guides/typescript/#path-aliases

`src` directory to host the `components` directory as a child?

**Comment by danstepanov** [comment]
Correct re import aliases and src but is just to have everything that isn't a configuration or entry file be in the `/src` directory. Not sure how that would work with expo router though. I'd be happy with just import alias tbh.
