### ISSUE TITLE
[docs] `/docs` 404s

### ISSUE THREAD

**Issue by danstepanov** [danstepanov/create-expo-stack#172]
## Expected Behavior

navigating to `createexpostack.com/docs` should reroute to `docs.createexpostack.com`

## Current Behavior

404

## Steps to Reproduce

1. Go to `https://createexpostack.com/docs`

**Comment by hqasmei** [comment]
Just made the update. Will create a PR rn

Before 
![Screenshot 2024-01-17 at 1 27 13 PM](https://github.com/danstepanov/create-expo-stack/assets/39573679/0e3d132e-38cf-49a6-bc99-d47e7fad6870)

After
![Screenshot 2024-01-17 at 1 27 32 PM](https://github.com/danstepanov/create-expo-stack/assets/39573679/8fb606a3-dea6-455f-8582-206776b05f49)
