### ISSUE TITLE
Misconfigured initialization for non-Typescript Project 

### ISSUE THREAD

**Issue by salman-ibrahim** [danstepanov/create-expo-stack#175]
I initialized a new project without Typescript support and it ended up initializing misconfigured Typescrtipt project.

## Expected Behavior

Files generated should have an extenstion of `.js` (or `.jsx`)

## Current Behavior

Choosing `false` on `Would you like to use TypeScript with this project?` ended up creating `.tsx` ( without jsx flag inside .tsconfig and no React imports in files)

## Possible Solution

--

## Steps to Reproduce

`npx create-expo-stack test-expo-stack --expo-router --tabs --tamagui --supabase --bun`

OR

1. `npx create-expo-stack`
2. `What do you want to name your project? (my-expo-app)` test-expo-stack
3.  `Would you like to use TypeScript with this project?` false
4. `What would you like to use for Navigation?` Expo Router
5. `What type of navigation would you like to use?` Tabs
6. `What would you like to use for styling?` Tamagui (experimental)
7. `What would you like to use for authentication?` Supabase
8. `Which package manager would you like to use?` bun

## Context (Environment)

Cannot start working on project without making necessary modifications like:
Either include `jsx` in `compilerOptions` of `.tsconfig` and import `React` in all the components OR rename all files to `.jsx` and remove all Type annotations from files.

- OS: MacOS
- Expo Stack: `create-expo-stack@2.3.14`
- Project Configuration:
```
{
  projectName: 'test-expo-stack',
  packages: [
    {
      name: 'expo-router',
      type: 'navigation',
      options: { type: 'tabs' }
    },
    { name: 'tamagui', type: 'styling' },
    { name: 'supabase', type: 'authentication' }
  ],
  flags: {
    noGit: false,
    noInstall: false,
    overwrite: false,
    importAlias: true,
    packageManager: 'bun'
  }
}
```

## Detailed Description

--

## Possible Implementation

--

**Comment by danstepanov** [comment]
create expo stack does not allow you to create a project without typescript. The question in the CLI that asks you whether you'd like to use typescript is there as a joke and if you say "no" then you'll see it says something like "wrong answer, you're using typescript." we do not plan to support creating a plain javascript option in setting up a project so I'll go ahead and close this.
