### ISSUE TITLE
Fails to launch app on both android and ios simulator with fresh create-stack-app

### ISSUE THREAD

**Issue by larssonted86** [danstepanov/create-expo-stack#176]
## Expected Behavior

app to be displayed

## Current Behavior

Trying to create a fresh app with create-stack-app > typescript > expo router with tabs stack or drawer > tamagui > firebase, install goes throug and i cd to project, run command run ios, or run android or npx expo start, simulators start, expo go is updated if needed then immediately I get  these errors

 ERROR  TypeError: 0, _expoModulesCore.requireOptionalNativeModule is not a function (it is undefined), js engine: hermes
 ERROR  TypeError: 0, _expoModulesCore.requireOptionalNativeModule is not a function (it is undefined), js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

## Steps to Reproduce

1. try to create a project with the create-stack-app cli

**Comment by danstepanov** [comment]
Confirmed, I recreated this on my end and it seems to primarily affect `npm` and `pnpm`. Apps initialized with `yarn` or `bun` don't seem to be affected.

Each of the following ends up running into the problem:
1. `npx create-expo-stack my-expo-app --nativewind --expo-router`
2. `npx create-expo-stack my-expo-app --tamagui --expo-router`
3. `npx create-expo-stack my-expo-app --nativewind --expo-router --pnpm`
4. `npx create-expo-stack my-expo-app --tamagui --expo-router --pnpm`

I tried a couple things from [this issue](https://github.com/expo/expo/issues/24409) to resolve it but no luck so far. 

I tried:
- Running `npx expo install --fix`
- Installing `expo-modules-core` via `npm i expo-modules-core`

I have not yet tried `npm i expo-modules-core@next`

**Comment by finnbayer** [comment]
Hey, I just tested `npm install expo-modules-core@latest` that fixed it on my end 🚀 . 

the `.requireOptionalNativeModule()` function was added in `expo-modules-core` v1.7 and put into use in v1.11 ([changelog](https://github.com/expo/expo/blob/main/packages/expo-modules-core/CHANGELOG.md#1110--2023-12-12)).
expo 49 adds expo-modules-core@1.5 to the dependency list. I don't really understand why it works with yarn/bun but I will try and look further into it in the next hour or so.

**Comment by danstepanov** [comment]
thanks so much @finnbayer, would you like to open a PR?

**Comment by danstepanov** [comment]
@larssonted86 Can you please try again with `npx create-expo-stack@latest`

**Comment by larssonted86** [comment]
@danstepanov project up and running 👍🏻 thanks for the quick help!
