### ISSUE TITLE
[cli] Type Error on Drawer + Tabs template for React Navigation

### ISSUE THREAD

**Issue by danstepanov** [danstepanov/create-expo-stack#191]
## Expected Behavior

No type errors

## Current Behavior

<img width="1041" alt="Screenshot 2024-01-27 at 3 11 55 AM" src="https://github.com/danstepanov/create-expo-stack/assets/5482800/7935179b-f655-4c3e-bb7e-3ffe48e69839">

## Possible Solution

No idea

## Steps to Reproduce

1. `npx create-expo-stack@next my-app --react-navigation --drawer+tabs` (can use any package manager)
2. Open newly generated project in code editor
3. Navigate to file `./src/navigation/drawer-navigator.tsx` lines 27 and 28

## Context (Environment)

Node v20.10.0
npm v10.2.3

**Comment by asapMaki** [comment]
@danstepanov Thank you for handling the rest of the tasks, much appreciated, Let me fix this one

**Comment by danstepanov** [comment]
@asapMaki for sure, also going to edit the commit adding drawer + tabs to be attributed to you, just way too tired atm, will do before release, thanks for your contributions!

**Comment by asapMaki** [comment]
First official open source commit 🚀  Thank you and your team for the welcoming experience
