### ISSUE TITLE
[cli] Delete all files if cli fails

### ISSUE THREAD

**Issue by danstepanov** [danstepanov/create-expo-stack#20]

**Comment by sammoore** [comment]
@danstepanov Re-opening this -- the refactor happened to support it (we now have `projectName` available within the `} catch (error) {` block) but [the TODO is still there](https://github.com/danstepanov/create-expo-stack/blob/main/cli/src/commands/create-expo-stack.ts#L315).

It's possible just uncommentting that line fixes it, but there may be edge cases. Will make this "good first issue".

**Comment by danstepanov** [comment]
@sammoore why was the delete files thing commented out rather than implemented?

**Comment by sammoore** [comment]
> @sammoore why was the delete files thing commented out rather than implemented?

No reason other than the fact that I was already testing the refactor with all it's edge cases, and wanted to get that merged in without also testing deleting files.

**Comment by danstepanov** [comment]
Word, I'll try to test this out today
