### ISSUE TITLE
[cli] Expo router problem after installing axios

### ISSUE THREAD

**Issue by Revaycolizer** [danstepanov/create-expo-stack#21]
I initialized a new app using npx create-expo-stack@latest but when I installed axios using npm install axios I got this error Module '.. /.. /components/edit-screen-info was resolved  to' d:/project/e-learning/components/edit-screen-infov.tsx' but '--jsx' is not set, i fixed it by adding jsx in my configuration file but now getting this error
![expoerror](https://github.com/danstepanov/create-expo-stack/assets/109684996/5e2cf2e0-20d5-4933-a792-a366251b7d35)

**Comment by danstepanov** [comment]
Hey I'll take a look at this on my flight today. Thanks for posting!

**Comment by Revaycolizer** [comment]
> Hey I'll take a look at this on my flight today. Thanks for posting!

Waiting

**Comment by danstepanov** [comment]
Just ran this command:

```
Your project configuration:
{
  projectName: 'my-expo-app',
  packages: [
    {
      name: 'expo-router',
      type: 'navigation',
      options: { type: 'tabs' }
    },
    { name: 'nativewind', type: 'styling' }
  ],
  flags: {
    noGit: false,
    noInstall: false,
    overwrite: false,
    importAlias: true,
    packageManager: 'npm'
  }
}

To recreate this project, run:
  npx create-expo-stack my-expo-app --expo-router --tabs --nativewind```
  
Then ran:

`npm install axios`

And lastly updated `./app/(tabs)/index.tsx` with the following code:

```
import * as React from 'react';
import { Text, View } from 'react-native';
import axios from 'axios';

import EditScreenInfo from '../../components/edit-screen-info';

export default function TabOneScreen() {
  React.useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      const response = await axios.get('https://jsonplaceholder.typicode.com/todos/1');
      console.log(response.data);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <View className={styles.container}>
      <Text className={styles.title}>Tab One</Text>
      <View className={styles.separator} />
      <EditScreenInfo path="app/(tabs)/index.tsx" />
    </View>
  );
}

const styles = {
  container: `items-center flex-1 justify-center`,
  separator: `h-[1px] my-7 w-4/5 bg-gray-200`,
  title: `text-xl font-bold`,
};
```

This properly returns the desired JSON object in the console.

Closing this issue as a non-issue until a proper repro is provided.
