### ISSUE TITLE
NativeWindUI wrong behavior!?

### ISSUE THREAD

**Issue by willerrodrigo** [danstepanov/create-expo-stack#277]
When choosing NativeWindUI the CLI does not continue to choose other options like navigation, authentication, etc. Is it correct?

<img width="669" alt="Screenshot 2024-04-30 at 11 14 52" src="https://github.com/danstepanov/create-expo-stack/assets/33837697/6ad7e518-f350-4ad2-9d67-d7a55951dc8c">

**Comment by danstepanov** [comment]
This is the expected behavior for now. We will gradually introduce those options. Doing so all at once is quite daunting.

**Comment by danstepanov** [comment]
@willerrodrigo this should be fixed in v2.10.2, can you please try `npx create-expo-stack@latest`?
