### ISSUE TITLE
Tsx files still for no typescript projects

### ISSUE THREAD

**Issue by Yubraj977** [danstepanov/create-expo-stack#308]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discord, in the #cli channel.

I tried to create project with typescript but it is generating typescript files

## Expected Behavior

It should create .js files in the place of .tsx files

## Current Behavior

[
![Screenshot from 2024-05-30 01-47-27](https://github.com/danstepanov/create-expo-stack/assets/112848654/6b2f86e3-bf36-40ed-8f38-50aa683a4ebd)
I have done this but still
![Screenshot from 2024-05-30 01-48-17](https://github.com/danstepanov/create-expo-stack/assets/112848654/6d55e133-997a-4ff6-bb04-27f945cc1155)
These tsx file are generating

## Context (Environment)
I am using ubutnu latest version

**Comment by danstepanov** [comment]
this is the intended behavior
