### ISSUE TITLE
New app creation has issues with Unable to resolve "react-native-css-interop/jsx-runtime" from "app/+not-found.tsx"

### ISSUE THREAD

**Issue by Julioevm** [danstepanov/create-expo-stack#312]
Hey, just tried to create a new app with the expo-stack to test it out and Im finding this issue:

I run `npx create-expo-stack` —I guess it will use the latest version—with the following settings: typescript, expo, nativewind, pnpm.

and I find the following error after running rpm run iOS and npm run start -> run on an iOS emulator.:

```
iOS Bundling failed 4905ms node_modules/.pnpm/[expo-router@3.5.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)5_@[react-navigation+drawer@6.6.15_expo-constants](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)@[16.0.2_expo-linking@6.3.1_e_w2bqchnxuvu2pijo7gyhudjniy](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/expo-router/entry.js (1093 modules) Unable to resolve "react-native-css-interop/jsx-runtime" from "app/+not-found.tsx"
```

## Expected Behavior

The app builds and runs correctly.

## Current Behavior

Error is thrown.

## Steps to Reproduce

Initialise the app with typescript, native wind and eas.

1. cd app folder
2. npm run iOS
3. launch on iOS emulator

## Context (Environment)

using a macOS m1 14.5 the iOS version is 17.2

**Comment by danstepanov** [comment]
Which version of CES are you using? 

`npx create-expo-stack --version`

**Comment by danstepanov** [comment]
Also please post the full output of the CLI

**Comment by Julioevm** [comment]
> Which version of CES are you using?
> 
> `npx create-expo-stack --version`

2.9.10

What do you want the full output of, npm run ios or the full set up output?

**Comment by dragoscv** [comment]
change the "main" inside app.json to the correct path

**Comment by danstepanov** [comment]
@Julioevm are you still running into this issue?

**Comment by joypatel04** [comment]
Sorry @danstepanov It was something else mostly i am gussing bun and i switched to yarn and everything is working fine. Thank you for yout help.
