### ISSUE TITLE
[cli] EAS setup support

### ISSUE THREAD

**Issue by agrittiwari** [danstepanov/create-expo-stack#4]
This CLI has scope to integrate the EAS setup support , that includes setting up the whole CI/CD pipeline across various environments and channels.

I've been experimenting with env variables and figuring out the right setup for our CI/CD. Let me know if this fits right in this. 
Would need some help to start.

**Comment by danstepanov** [comment]
that would be sick! would love to see more of what you have in mind, please note the architectural change in this PR https://github.com/danstepanov/create-expo-stack/pull/6, happy to chat in discord :)

**Comment by danstepanov** [comment]
@agrittiwari you should be good to start working on this now that v2.1 is out :)

**Comment by geoman2** [comment]
Maybe you expand this feature to use on-premise CI/CD, not be dependent on expo servers. There are various solutions to achieve this I found  https://github.com/filipeforattini/ff-iac-github-actions/blob/main/.github/workflows/mob.yml
Also https://github.com/callstack/react-native-builder-bob
What do you say?

**Comment by danstepanov** [comment]
@geoman2 will explore more options as we introduce the popular ones, PRs are always welcome!
