### ISSUE TITLE
[www] add github star count next to our github logo

### ISSUE THREAD

**Issue by danstepanov** [danstepanov/create-expo-stack#46]
Example:

![image](https://github.com/danstepanov/create-expo-stack/assets/5482800/ee999c58-cfa9-4fd5-9ddf-8cf67d836cd8)

**Comment by Sahad-09** [comment]
I'm working on this

**Comment by danstepanov** [comment]
There's a great example of it on the T3 website https://create.t3.gg

**Comment by Sahad-09** [comment]
Yeah, already referred and coded. Just arranging the code and making it readable rn

**Comment by Sahad-09** [comment]
![stars](https://github.com/danstepanov/create-expo-stack/assets/91364349/fe163ef9-82c3-4577-8504-738cff418bc6)
Is this okay ? Or is there any specific design in mind

**Comment by todevmilen** [comment]
Hi there! Do you like this kind of design ?

![image](https://github.com/danstepanov/create-expo-stack/assets/78319110/dac4ad8d-5aea-4dd7-9a1f-182f736c9487)
