### ISSUE TITLE
[docs] provide proper feedback with instructions about the release workflow

### ISSUE THREAD

**Issue by ernestoresende** [danstepanov/create-expo-stack#63]
Currently, new contributors are clueless on what their role is for automated releases to work. 

There are two steps that need to be taken in order to somewhat fix that:
- [x] Update both the contribution guidelines and the PR templates with instructions on how to properly create, manage and name changesets for releases. PR templates should probably have a checklist option regarding this.
- [x] Use the `changeset-bot` GitHub app to auto-comment on PR's giving feedback on the status of the changesets.

**Comment by ernestoresende** [comment]
I believe its almost there, `CONTRIBUTING.md` now has a few paragraphs dedicated to explaining the role of changesets and how to operate then within the project.

Before closing this I would like to complete it as a whole:
- Add the Changeset bot to verify pull requests;
- Add a checklist option for PR templates where contributors can tick the box for something like: "I have added a changeset with my changes, if relevant" or similar wording.

**Comment by danstepanov** [comment]
Agree on all fronts, feel free to implement as soon as you're available to.

**Comment by danstepanov** [comment]
@ernestoresende status on this?

**Comment by danstepanov** [comment]
@ernestoresende I have added the bot to the repository, please feel free to configure it as you and @sammoore see fit. I'll let y'all close this issue when you feel it is appropriate to do so.

**Comment by ernestoresende** [comment]
I see the bot taking action on some of the the latest PR's, so I think we're good here 🚀
