### ISSUE TITLE
[cli] Upgrade to NativeWind v4

### ISSUE THREAD

**Issue by danstepanov** [danstepanov/create-expo-stack#70]
Mark recently released NativeWind v4, we should upgrade existing templates to use this version. v4 has a new way of configuring NativeWind so that will likely be the bulk of the work. I believe that the styles are still passed in the same way.

https://www.nativewind.dev/v4/overview

**Comment by RobSchilderr** [comment]
Would really be interested in this!

**Comment by danstepanov** [comment]
Any interest in implementing it? I can't imagine it would be difficult.

**Comment by RobSchilderr** [comment]
> Any interest in implementing it? I can't imagine it would be difficult.

I will be happy to test it out but not in the position to implement it for the foreseeable future. Having my eye on this issue!

**Comment by danstepanov** [comment]
https://github.com/marklawlor/nativewind/issues/600

**Comment by danstepanov** [comment]
This is pending the next release of nativewind v4, per Mark Lawlor

**Comment by danstepanov** [comment]
Installation for Expo but not Expo Router: https://www.nativewind.dev/v4/getting-started/react-native

Installation for Expo Router: https://www.nativewind.dev/v4/getting-started/expo-router

I will be adding this as `Nativewind v4 (experimental)` in addition ot the standard `Nativewind`

**Comment by danstepanov** [comment]
Closing as this was just merged in via https://github.com/danstepanov/create-expo-stack/pull/193
