### ISSUE TITLE
error while running format script

### ISSUE THREAD

**Issue by kratos-respawned** [danstepanov/create-expo-stack#73]
Getting the following error while running npm run format script 
```No files matching the pattern "'**/*.{js,jsx,ts,tsx}'" were found.```

**Comment by danstepanov** [comment]
Can you share the full output of running create expo stack?

**Comment by kratos-respawned** [comment]
![image](https://github.com/danstepanov/create-expo-stack/assets/87561983/e7fd6955-fe9c-443a-85b3-b4425fbc1f51)

I've created a PR[#72 ] to patch this

**Comment by frankcalise** [comment]
Can this be closed due to https://github.com/danstepanov/create-expo-stack/pull/83?
