### ISSUE TITLE
[cli][www][FR] Auth providers

### ISSUE THREAD

**Issue by danstepanov** [danstepanov/create-expo-stack#9]
## Why

Many people inquire about how to best get set up with an auth provider and create-expo-stack seems like a great way to convey this. Additionally, in order to support flags for other opinionated stacks, we might need to support auth providers out of the box.

## What

Add a CLI option to select an auth provider (likely Supabase or Firebase, open to others).

## How

There are more set up steps beyond just the mobile code configuration so this should contain both a minimal example set up with each auth provider as well as a link to some kind of walkthrough that highlights how to create an account, acquire keys, and familiarize with the relevant dashboard.

**Comment by nateemerson** [comment]
> as well as a link to some kind of walkthrough

where might this walkthrough be hosted? Do we have a docs site?

Regardless I’d recommend splitting this into its own docs ticket (“Auth setup walkthrough”).

**Comment by danstepanov** [comment]
@nateemerson done
