### ISSUE TITLE
Web hydration error on fresh project creation

### ISSUE THREAD

**Issue by rhlabsuk** [danstepanov/create-expo-stack#91]
I am seeing a hydration error with a fresh project using the following command:

```bash
npx create-expo-stack@latest my-expo-app --expo-router --tabs --nativewind --supabase --bun
```

This appears to not give any errors when loading through an iOS simulator, or deploying via Vercel and viewing on the web.

![image](https://github.com/danstepanov/create-expo-stack/assets/4499929/be6bf9c3-eefe-4efc-882d-23b2bd814c96)

**Comment by danstepanov** [comment]
@Ryan-Harvey which command are you running to see this error? Is this `expo start --web`? If so, we don't support web first class at the moment. We are primarily focused on native but can dig into web in the coming weeks.

**Comment by danstepanov** [comment]
able to recreate with the above command, @frankcalise do y'all ever run into this kind of error with ignite?

**Comment by frankcalise** [comment]
@danstepanov haven't seen an error message like this before but I'll repro it and take a look tomorrow

**Comment by frankcalise** [comment]
@danstepanov https://github.com/marklawlor/nativewind/issues/523#issuecomment-1791866675

seems like we need #70

**Comment by danstepanov** [comment]
@frankcalise while I am no longer running into the same error above when running `bun run web`, I am now running into a different error when running that same command. Have you seen this with Ignite or elsewhere?

Seems like we're missing some files that we should be including?

To recreate:

`npx create-expo-stack@latest my-expo-app --expo-router --tabs --nativewind --supabase --bun`

![Screenshot 2024-04-04 at 4 40 50 PM](https://github.com/danstepanov/create-expo-stack/assets/5482800/0f615d23-b078-4dde-814d-d35dc8717c34)

**Comment by frankcalise** [comment]
@danstepanov I haven't seen this on Ignite but we don't really use nativewind at all

**Comment by danstepanov** [comment]
Since upgrading to NativeWind v4, this is no longer an issue. However, there is a race condition with NativeWind that is being worked on pertaining to `global.css`. Due to this issue, you're run into the following error.

```
Unable to resolve module /Users/dan/my-expo-app/node_modules/.cache/nativewind/global.css from /Users/dan/my-expo-app/global.css
```
