### ISSUE TITLE
api/og not working with Astro

### ISSUE THREAD

**Issue by hqasmei** [danstepanov/create-expo-stack#94]
To use open graph with Astro, currently using the image from the public file called og-image.png. 
Need to figure out how api/og.tsx works with Astro, says in the Vercel docs needs to be ran on edge.
But we are in static mode in the astro.config.mjs file. Need to look into this more.

Resources:
- https://vercel.com/docs/functions/edge-functions/og-image-generation#examples

**Comment by danstepanov** [comment]
this is temporarily fixed with static assets but is not using the automatically generated image based on jsx code

**Comment by ernestoresende** [comment]
@danstepanov @hqasmei Is the objective here to have dynamic OG generation based on the docs page content metadata? Also, do we already have a defined design/layout for how they should look like?

If so, we can probably achieve this with `@vercel/og` (https://www.kozhuhds.com/blog/generating-static-open-graph-og-images-in-astro-using-vercel-og) and an [on-demand server rendering](https://docs.astro.build/en/guides/server-side-rendering/). For a while now, Astro allows to be partial about what parts of the Astro application we want to run on the server, while keeping the rest of the application static.

**Comment by danstepanov** [comment]
The goal would be to have custom previews for different pages of the website (docs, landing, etc). [We used to have code generated images prior to the migration to astro](https://github.com/danstepanov/create-expo-stack/blob/026b97ee02f370ee1ee10dad9877b540a3c623d7/www/src/app/api/og/route.tsx).

**Comment by hqasmei** [comment]
Hey @ernestoresende thanks for sharing those resources. Will check them out. 
For the www repo, I think when we were working on it we set the output as static. Forgot why. It wasn't working otherwise. 
For the docs repo, I don't believe we have the output set to anything so I'll try to see if we can get the @vercel/og image working there.

<img width="377" alt="Screenshot 2024-01-10 at 12 22 27 PM" src="https://github.com/danstepanov/create-expo-stack/assets/39573679/3b0074b2-0782-4456-ae04-90616746e9ae">

**Comment by hqasmei** [comment]
Hey @danstepanov what would you want the custom previews look like?
The previous code you doesn't seem like it's dynamic. Would you want something similar to Next.js, have the log in the center with the title underneath?
<img width="407" alt="Screenshot 2024-01-10 at 12 29 29 PM" src="https://github.com/danstepanov/create-expo-stack/assets/39573679/d6786db3-3a3e-4bfe-a978-f7bbe8e49400">

**Comment by hqasmei** [comment]
Created a branch docs/og, I updated the code, the og image is in the head but the og image isn't loading it gives me this.
Im using the preview generated by vercel, not sure if it's a server setup thing. 

<img width="1448" alt="Screenshot 2024-01-10 at 2 31 57 PM" src="https://github.com/danstepanov/create-expo-stack/assets/39573679/4a46532d-6875-460b-a0e5-985c09154c4e">

**Comment by hqasmei** [comment]
https://github.com/danstepanov/create-expo-stack/blob/docs/og/docs/astro.config.mjs

<img width="489" alt="Screenshot 2024-01-10 at 2 35 46 PM" src="https://github.com/danstepanov/create-expo-stack/assets/39573679/75d9ad9b-ef9b-401a-8d73-17c96ce7b803">

**Comment by hqasmei** [comment]
Was figured out can find more about in PR #184
